#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Source work specific functions if they exist
if [[ -f "${ZDOTDIR:-$HOME}/.zshrc_work" ]]; then
  Source "${ZDOTDIR:-$HOME}/.zshrc_work"
fi